name: First workflow
on: [workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello to world of Github action!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: Run multiline commands
        run: |
          echo "current date is ${date}"
          echo "I am : ${whoami}"
  
